name: build and unit tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: setup virtual env
        run: python3 -m venv .venv

      - name: setup packages
        run: |
          . .venv/bin/activate
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: audit dependencies
        run: |
          . .venv/bin/activate
          pip install pip-audit
          pip-audit -r requirements.txt

      - name: algorithm tests
        run: |
          . .venv/bin/activate
          pytest -v
