name: dotnet build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: setup virtual env
        run: python3 -m venv .venv

      - name: setup packages
        run: |
          . .venv/bin/activate
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: algorithm tests
        run: |
          . .venv/bin/activate
          python bernstein_vazirani_quantum.py
          python deutsch_classical.py
          python deutsch_jozsa_quantum.py
          python deutsch_quantum.py
          python sat_quantum.py
